name: ColorBukkit
api-version: 1.17
version: "0.0.1-SNAPSHOT"
description: A plugin which allows for an in game color selection.
author: Thorinwasher
main: dev.thorinwasher.utils.colorbukkit.ColorBukkit
commands: 
  colorbukkit:
    description: Used to get a color hexcode.
  cw:
    description: Used internally.
permissions:
   colorbukkit:
     default: false
     description: Display a collorpicker gui, after selection display the selected color in chat