name: ColorBukkit
api-version: 1.17
version: "0.0.1-SNAPSHOT"
description: A plugin which allows for an in game color selection.
author: Thorinwasher
main: dev.thorinwasher.colorbukkit.ColorBukkit
commands: 
  colorbukkit:
    description: Used to get a color hexcode.
  cw:
    description: Used internally.